on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies for sf
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes","pkgdown","knitr","rmarkdown","systemfonts","ragg","textshaping"))
          remotes::install_github("redivis/redivis-r", ref = "main")
          remotes::install_deps(dependencies = NA, upgrade = "never")
          remotes::install_local(dependencies = NA, upgrade = "never")
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Upload artifact for GitHub Pages deployment
        uses: actions/upload-artifact@v4
        with:
          name: pkgdown-docs
          path: docs
          overwrite: true

  deploy:
    needs: pkgdown
    runs-on: ubuntu-latest
    steps:
      - name: Download Built Site Artifact
        uses: actions/download-artifact@v4
        with:
          name: pkgdown-docs
          path: docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v4